"use client";

import { useEffect, useState } from "react";
import { LatexEditor } from "@/components/latex/latex-editor";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import api, { type Paper } from "@/lib/api";
import { FileCode2 } from "lucide-react";

const SCRATCH_ID = "__scratch__";

export default function LatexEditorPage() {
  const [papers, setPapers] = useState<Paper[]>([]);
  const [selectedId, setSelectedId] = useState<string>(SCRATCH_ID);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    api
      .getPapers({ per_page: "100" })
      .then((res) => setPapers(res.items))
      .catch(() => setPapers([]))
      .finally(() => setLoading(false));
  }, []);

  const selectedPaper = papers.find((p) => p.id === selectedId) ?? null;

  return (
    <div className="flex flex-col h-[calc(100vh-5rem)] gap-0">
      {/* ── Page header ─────────────────────────────────────── */}
      <div className="flex items-center gap-4 px-4 py-3 border-b bg-card shrink-0">
        <div className="flex items-center gap-2 min-w-0">
          <FileCode2 className="h-5 w-5 text-primary shrink-0" />
          <h1 className="text-lg font-semibold tracking-tight truncate">
            LaTeX Editor
          </h1>
        </div>

        <div className="flex items-center gap-2 ml-auto">
          <span className="text-sm text-muted-foreground whitespace-nowrap">
            Paper:
          </span>
          {loading ? (
            <Skeleton className="h-8 w-52" />
          ) : (
            <div>
              <Select value={selectedId} onValueChange={(v) => setSelectedId(v ?? SCRATCH_ID)}>
                <SelectTrigger className="w-64 h-8 text-sm">
                  <SelectValue placeholder="Select a paper…" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value={SCRATCH_ID}>
                    — Scratch / New Document —
                  </SelectItem>
                  {papers.map((p) => (
                    <SelectItem key={p.id} value={p.id}>
                      {p.title.length > 50
                        ? p.title.slice(0, 47) + "…"
                        : p.title}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {papers.length === 100 && (
                <p className="text-xs text-muted-foreground mt-1">
                  Showing first 100 papers. Use search to find others.
                </p>
              )}
            </div>
          )}
        </div>
      </div>

      {/* ── Editor area ─────────────────────────────────────── */}
      <div className="flex-1 overflow-hidden border rounded-b-lg">
        {loading ? (
          <div className="p-6 space-y-4">
            <Skeleton className="h-8 w-full" />
            <Skeleton className="h-[60vh] w-full" />
          </div>
        ) : (
          /*
           * Key on selectedId so React fully remounts the editor (and its
           * CodeMirror instance) whenever the user switches papers.
           */
          <LatexEditor
            key={selectedId}
            paperId={selectedId}
            initialTex={
              selectedPaper
                ? `% Paper: ${selectedPaper.title}\n% Generated by PaperPilot\n`
                : undefined
            }
          />
        )}
      </div>
    </div>
  );
}
